// Code generated by "stringer -type=Level"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[OK-1]
	_ = x[Issues-2]
	_ = x[Warning-3]
	_ = x[Down-4]
}

const _Level_name = "UnknownOKIssuesWarningDown"

var _Level_index = [...]uint8{0, 7, 9, 15, 22, 26}

func (i Level) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Level_index)-1 {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[idx]:_Level_index[idx+1]]
}
