// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (i *Incident) Counters(ctx context.Context) ([]*Counter, error) {
	result, err := i.NamedCounters(graphql.GetFieldContext(ctx).Field.Alias)
	if IsNotLoaded(err) {
		result, err = i.QueryCounters().All(ctx)
	}
	return result, err
}

func (i *Incident) Stati(ctx context.Context) ([]*Status, error) {
	result, err := i.NamedStati(graphql.GetFieldContext(ctx).Field.Alias)
	if IsNotLoaded(err) {
		result, err = i.QueryStati().All(ctx)
	}
	return result, err
}

func (i *Incident) Failures(ctx context.Context) ([]*Failure, error) {
	result, err := i.NamedFailures(graphql.GetFieldContext(ctx).Field.Alias)
	if IsNotLoaded(err) {
		result, err = i.QueryFailures().All(ctx)
	}
	return result, err
}
