// Code generated by ent, DO NOT EDIT.

package failure

const (
	// Label holds the string label denoting the failure type in the database.
	Label = "failure"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldIdx holds the string denoting the idx field in the database.
	FieldIdx = "idx"
	// Table holds the table name of the failure in the database.
	Table = "failures"
)

// Columns holds all SQL columns for failure fields.
var Columns = []string{
	FieldID,
	FieldError,
	FieldIdx,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "failures"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"alert_failures",
	"incident_failures",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
