// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/alert"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/counter"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/failure"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/file"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/predicate"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/status"
)

// AlertUpdate is the builder for updating Alert entities.
type AlertUpdate struct {
	config
	hooks    []Hook
	mutation *AlertMutation
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdate) Where(ps ...predicate.Alert) *AlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUUID sets the "UUID" field.
func (_u *AlertUpdate) SetUUID(v uuid.UUID) *AlertUpdate {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "UUID" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableUUID(v *uuid.UUID) *AlertUpdate {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetIncidentID sets the "IncidentID" field.
func (_u *AlertUpdate) SetIncidentID(v uuid.UUID) *AlertUpdate {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "IncidentID" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableIncidentID(v *uuid.UUID) *AlertUpdate {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// ClearIncidentID clears the value of the "IncidentID" field.
func (_u *AlertUpdate) ClearIncidentID() *AlertUpdate {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetName sets the "Name" field.
func (_u *AlertUpdate) SetName(v string) *AlertUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableName(v *string) *AlertUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTime sets the "Time" field.
func (_u *AlertUpdate) SetTime(v time.Time) *AlertUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "Time" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableTime(v *time.Time) *AlertUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetIntLevel sets the "IntLevel" field.
func (_u *AlertUpdate) SetIntLevel(v int) *AlertUpdate {
	_u.mutation.ResetIntLevel()
	_u.mutation.SetIntLevel(v)
	return _u
}

// SetNillableIntLevel sets the "IntLevel" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableIntLevel(v *int) *AlertUpdate {
	if v != nil {
		_u.SetIntLevel(*v)
	}
	return _u
}

// AddIntLevel adds value to the "IntLevel" field.
func (_u *AlertUpdate) AddIntLevel(v int) *AlertUpdate {
	_u.mutation.AddIntLevel(v)
	return _u
}

// SetUsername sets the "Username" field.
func (_u *AlertUpdate) SetUsername(v string) *AlertUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "Username" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableUsername(v *string) *AlertUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetRegion sets the "Region" field.
func (_u *AlertUpdate) SetRegion(v string) *AlertUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "Region" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableRegion(v *string) *AlertUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetProbeOS sets the "ProbeOS" field.
func (_u *AlertUpdate) SetProbeOS(v string) *AlertUpdate {
	_u.mutation.SetProbeOS(v)
	return _u
}

// SetNillableProbeOS sets the "ProbeOS" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableProbeOS(v *string) *AlertUpdate {
	if v != nil {
		_u.SetProbeOS(*v)
	}
	return _u
}

// SetProbeHost sets the "ProbeHost" field.
func (_u *AlertUpdate) SetProbeHost(v string) *AlertUpdate {
	_u.mutation.SetProbeHost(v)
	return _u
}

// SetNillableProbeHost sets the "ProbeHost" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableProbeHost(v *string) *AlertUpdate {
	if v != nil {
		_u.SetProbeHost(*v)
	}
	return _u
}

// SetError sets the "Error" field.
func (_u *AlertUpdate) SetError(v string) *AlertUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "Error" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableError(v *string) *AlertUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "Error" field.
func (_u *AlertUpdate) ClearError() *AlertUpdate {
	_u.mutation.ClearError()
	return _u
}

// AddCounterIDs adds the "Counters" edge to the Counter entity by IDs.
func (_u *AlertUpdate) AddCounterIDs(ids ...int) *AlertUpdate {
	_u.mutation.AddCounterIDs(ids...)
	return _u
}

// AddCounters adds the "Counters" edges to the Counter entity.
func (_u *AlertUpdate) AddCounters(v ...*Counter) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCounterIDs(ids...)
}

// AddStatiIDs adds the "Stati" edge to the Status entity by IDs.
func (_u *AlertUpdate) AddStatiIDs(ids ...int) *AlertUpdate {
	_u.mutation.AddStatiIDs(ids...)
	return _u
}

// AddStati adds the "Stati" edges to the Status entity.
func (_u *AlertUpdate) AddStati(v ...*Status) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatiIDs(ids...)
}

// AddFailureIDs adds the "Failures" edge to the Failure entity by IDs.
func (_u *AlertUpdate) AddFailureIDs(ids ...int) *AlertUpdate {
	_u.mutation.AddFailureIDs(ids...)
	return _u
}

// AddFailures adds the "Failures" edges to the Failure entity.
func (_u *AlertUpdate) AddFailures(v ...*Failure) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFailureIDs(ids...)
}

// AddFileIDs adds the "Files" edge to the File entity by IDs.
func (_u *AlertUpdate) AddFileIDs(ids ...int) *AlertUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "Files" edges to the File entity.
func (_u *AlertUpdate) AddFiles(v ...*File) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdate) Mutation() *AlertMutation {
	return _u.mutation
}

// ClearCounters clears all "Counters" edges to the Counter entity.
func (_u *AlertUpdate) ClearCounters() *AlertUpdate {
	_u.mutation.ClearCounters()
	return _u
}

// RemoveCounterIDs removes the "Counters" edge to Counter entities by IDs.
func (_u *AlertUpdate) RemoveCounterIDs(ids ...int) *AlertUpdate {
	_u.mutation.RemoveCounterIDs(ids...)
	return _u
}

// RemoveCounters removes "Counters" edges to Counter entities.
func (_u *AlertUpdate) RemoveCounters(v ...*Counter) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCounterIDs(ids...)
}

// ClearStati clears all "Stati" edges to the Status entity.
func (_u *AlertUpdate) ClearStati() *AlertUpdate {
	_u.mutation.ClearStati()
	return _u
}

// RemoveStatiIDs removes the "Stati" edge to Status entities by IDs.
func (_u *AlertUpdate) RemoveStatiIDs(ids ...int) *AlertUpdate {
	_u.mutation.RemoveStatiIDs(ids...)
	return _u
}

// RemoveStati removes "Stati" edges to Status entities.
func (_u *AlertUpdate) RemoveStati(v ...*Status) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatiIDs(ids...)
}

// ClearFailures clears all "Failures" edges to the Failure entity.
func (_u *AlertUpdate) ClearFailures() *AlertUpdate {
	_u.mutation.ClearFailures()
	return _u
}

// RemoveFailureIDs removes the "Failures" edge to Failure entities by IDs.
func (_u *AlertUpdate) RemoveFailureIDs(ids ...int) *AlertUpdate {
	_u.mutation.RemoveFailureIDs(ids...)
	return _u
}

// RemoveFailures removes "Failures" edges to Failure entities.
func (_u *AlertUpdate) RemoveFailures(v ...*Failure) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFailureIDs(ids...)
}

// ClearFiles clears all "Files" edges to the File entity.
func (_u *AlertUpdate) ClearFiles() *AlertUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "Files" edge to File entities by IDs.
func (_u *AlertUpdate) RemoveFileIDs(ids ...int) *AlertUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "Files" edges to File entities.
func (_u *AlertUpdate) RemoveFiles(v ...*File) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(alert.FieldUUID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IncidentID(); ok {
		_spec.SetField(alert.FieldIncidentID, field.TypeUUID, value)
	}
	if _u.mutation.IncidentIDCleared() {
		_spec.ClearField(alert.FieldIncidentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(alert.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(alert.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IntLevel(); ok {
		_spec.SetField(alert.FieldIntLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntLevel(); ok {
		_spec.AddField(alert.FieldIntLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(alert.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(alert.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeOS(); ok {
		_spec.SetField(alert.FieldProbeOS, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeHost(); ok {
		_spec.SetField(alert.FieldProbeHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(alert.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(alert.FieldError, field.TypeString)
	}
	if _u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.CountersTable,
			Columns: []string{alert.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCountersIDs(); len(nodes) > 0 && !_u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.CountersTable,
			Columns: []string{alert.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CountersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.CountersTable,
			Columns: []string{alert.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.StatiTable,
			Columns: []string{alert.StatiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatiIDs(); len(nodes) > 0 && !_u.mutation.StatiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.StatiTable,
			Columns: []string{alert.StatiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.StatiTable,
			Columns: []string{alert.StatiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FailuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FailuresTable,
			Columns: []string{alert.FailuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFailuresIDs(); len(nodes) > 0 && !_u.mutation.FailuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FailuresTable,
			Columns: []string{alert.FailuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FailuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FailuresTable,
			Columns: []string{alert.FailuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FilesTable,
			Columns: []string{alert.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FilesTable,
			Columns: []string{alert.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FilesTable,
			Columns: []string{alert.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertUpdateOne is the builder for updating a single Alert entity.
type AlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertMutation
}

// SetUUID sets the "UUID" field.
func (_u *AlertUpdateOne) SetUUID(v uuid.UUID) *AlertUpdateOne {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "UUID" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableUUID(v *uuid.UUID) *AlertUpdateOne {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetIncidentID sets the "IncidentID" field.
func (_u *AlertUpdateOne) SetIncidentID(v uuid.UUID) *AlertUpdateOne {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "IncidentID" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableIncidentID(v *uuid.UUID) *AlertUpdateOne {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// ClearIncidentID clears the value of the "IncidentID" field.
func (_u *AlertUpdateOne) ClearIncidentID() *AlertUpdateOne {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetName sets the "Name" field.
func (_u *AlertUpdateOne) SetName(v string) *AlertUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableName(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTime sets the "Time" field.
func (_u *AlertUpdateOne) SetTime(v time.Time) *AlertUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "Time" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableTime(v *time.Time) *AlertUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetIntLevel sets the "IntLevel" field.
func (_u *AlertUpdateOne) SetIntLevel(v int) *AlertUpdateOne {
	_u.mutation.ResetIntLevel()
	_u.mutation.SetIntLevel(v)
	return _u
}

// SetNillableIntLevel sets the "IntLevel" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableIntLevel(v *int) *AlertUpdateOne {
	if v != nil {
		_u.SetIntLevel(*v)
	}
	return _u
}

// AddIntLevel adds value to the "IntLevel" field.
func (_u *AlertUpdateOne) AddIntLevel(v int) *AlertUpdateOne {
	_u.mutation.AddIntLevel(v)
	return _u
}

// SetUsername sets the "Username" field.
func (_u *AlertUpdateOne) SetUsername(v string) *AlertUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "Username" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableUsername(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetRegion sets the "Region" field.
func (_u *AlertUpdateOne) SetRegion(v string) *AlertUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "Region" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableRegion(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetProbeOS sets the "ProbeOS" field.
func (_u *AlertUpdateOne) SetProbeOS(v string) *AlertUpdateOne {
	_u.mutation.SetProbeOS(v)
	return _u
}

// SetNillableProbeOS sets the "ProbeOS" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableProbeOS(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetProbeOS(*v)
	}
	return _u
}

// SetProbeHost sets the "ProbeHost" field.
func (_u *AlertUpdateOne) SetProbeHost(v string) *AlertUpdateOne {
	_u.mutation.SetProbeHost(v)
	return _u
}

// SetNillableProbeHost sets the "ProbeHost" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableProbeHost(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetProbeHost(*v)
	}
	return _u
}

// SetError sets the "Error" field.
func (_u *AlertUpdateOne) SetError(v string) *AlertUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "Error" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableError(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "Error" field.
func (_u *AlertUpdateOne) ClearError() *AlertUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// AddCounterIDs adds the "Counters" edge to the Counter entity by IDs.
func (_u *AlertUpdateOne) AddCounterIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.AddCounterIDs(ids...)
	return _u
}

// AddCounters adds the "Counters" edges to the Counter entity.
func (_u *AlertUpdateOne) AddCounters(v ...*Counter) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCounterIDs(ids...)
}

// AddStatiIDs adds the "Stati" edge to the Status entity by IDs.
func (_u *AlertUpdateOne) AddStatiIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.AddStatiIDs(ids...)
	return _u
}

// AddStati adds the "Stati" edges to the Status entity.
func (_u *AlertUpdateOne) AddStati(v ...*Status) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatiIDs(ids...)
}

// AddFailureIDs adds the "Failures" edge to the Failure entity by IDs.
func (_u *AlertUpdateOne) AddFailureIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.AddFailureIDs(ids...)
	return _u
}

// AddFailures adds the "Failures" edges to the Failure entity.
func (_u *AlertUpdateOne) AddFailures(v ...*Failure) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFailureIDs(ids...)
}

// AddFileIDs adds the "Files" edge to the File entity by IDs.
func (_u *AlertUpdateOne) AddFileIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "Files" edges to the File entity.
func (_u *AlertUpdateOne) AddFiles(v ...*File) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdateOne) Mutation() *AlertMutation {
	return _u.mutation
}

// ClearCounters clears all "Counters" edges to the Counter entity.
func (_u *AlertUpdateOne) ClearCounters() *AlertUpdateOne {
	_u.mutation.ClearCounters()
	return _u
}

// RemoveCounterIDs removes the "Counters" edge to Counter entities by IDs.
func (_u *AlertUpdateOne) RemoveCounterIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.RemoveCounterIDs(ids...)
	return _u
}

// RemoveCounters removes "Counters" edges to Counter entities.
func (_u *AlertUpdateOne) RemoveCounters(v ...*Counter) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCounterIDs(ids...)
}

// ClearStati clears all "Stati" edges to the Status entity.
func (_u *AlertUpdateOne) ClearStati() *AlertUpdateOne {
	_u.mutation.ClearStati()
	return _u
}

// RemoveStatiIDs removes the "Stati" edge to Status entities by IDs.
func (_u *AlertUpdateOne) RemoveStatiIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.RemoveStatiIDs(ids...)
	return _u
}

// RemoveStati removes "Stati" edges to Status entities.
func (_u *AlertUpdateOne) RemoveStati(v ...*Status) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatiIDs(ids...)
}

// ClearFailures clears all "Failures" edges to the Failure entity.
func (_u *AlertUpdateOne) ClearFailures() *AlertUpdateOne {
	_u.mutation.ClearFailures()
	return _u
}

// RemoveFailureIDs removes the "Failures" edge to Failure entities by IDs.
func (_u *AlertUpdateOne) RemoveFailureIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.RemoveFailureIDs(ids...)
	return _u
}

// RemoveFailures removes "Failures" edges to Failure entities.
func (_u *AlertUpdateOne) RemoveFailures(v ...*Failure) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFailureIDs(ids...)
}

// ClearFiles clears all "Files" edges to the File entity.
func (_u *AlertUpdateOne) ClearFiles() *AlertUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "Files" edge to File entities by IDs.
func (_u *AlertUpdateOne) RemoveFileIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "Files" edges to File entities.
func (_u *AlertUpdateOne) RemoveFiles(v ...*File) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdateOne) Where(ps ...predicate.Alert) *AlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertUpdateOne) Select(field string, fields ...string) *AlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Alert entity.
func (_u *AlertUpdateOne) Save(ctx context.Context) (*Alert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdateOne) SaveX(ctx context.Context) *Alert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AlertUpdateOne) sqlSave(ctx context.Context) (_node *Alert, err error) {
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Alert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alert.FieldID)
		for _, f := range fields {
			if !alert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(alert.FieldUUID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IncidentID(); ok {
		_spec.SetField(alert.FieldIncidentID, field.TypeUUID, value)
	}
	if _u.mutation.IncidentIDCleared() {
		_spec.ClearField(alert.FieldIncidentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(alert.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(alert.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IntLevel(); ok {
		_spec.SetField(alert.FieldIntLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntLevel(); ok {
		_spec.AddField(alert.FieldIntLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(alert.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(alert.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeOS(); ok {
		_spec.SetField(alert.FieldProbeOS, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeHost(); ok {
		_spec.SetField(alert.FieldProbeHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(alert.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(alert.FieldError, field.TypeString)
	}
	if _u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.CountersTable,
			Columns: []string{alert.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCountersIDs(); len(nodes) > 0 && !_u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.CountersTable,
			Columns: []string{alert.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CountersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.CountersTable,
			Columns: []string{alert.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.StatiTable,
			Columns: []string{alert.StatiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatiIDs(); len(nodes) > 0 && !_u.mutation.StatiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.StatiTable,
			Columns: []string{alert.StatiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.StatiTable,
			Columns: []string{alert.StatiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FailuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FailuresTable,
			Columns: []string{alert.FailuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFailuresIDs(); len(nodes) > 0 && !_u.mutation.FailuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FailuresTable,
			Columns: []string{alert.FailuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FailuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FailuresTable,
			Columns: []string{alert.FailuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FilesTable,
			Columns: []string{alert.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FilesTable,
			Columns: []string{alert.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.FilesTable,
			Columns: []string{alert.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Alert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
