// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/alert"
)

// Alert is the model entity for the Alert schema.
type Alert struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "UUID" field.
	UUID uuid.UUID `json:"UUID,omitempty"`
	// IncidentID holds the value of the "IncidentID" field.
	IncidentID uuid.UUID `json:"IncidentID,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Time holds the value of the "Time" field.
	Time time.Time `json:"Time,omitempty"`
	// IntLevel holds the value of the "IntLevel" field.
	IntLevel int `json:"IntLevel,omitempty"`
	// Username holds the value of the "Username" field.
	Username string `json:"Username,omitempty"`
	// Region holds the value of the "Region" field.
	Region string `json:"Region,omitempty"`
	// ProbeOS holds the value of the "ProbeOS" field.
	ProbeOS string `json:"ProbeOS,omitempty"`
	// ProbeHost holds the value of the "ProbeHost" field.
	ProbeHost string `json:"ProbeHost,omitempty"`
	// Error holds the value of the "Error" field.
	Error string `json:"Error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertQuery when eager-loading is set.
	Edges        AlertEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertEdges holds the relations/edges for other nodes in the graph.
type AlertEdges struct {
	// Counters holds the value of the Counters edge.
	Counters []*Counter `json:"Counters,omitempty"`
	// Stati holds the value of the Stati edge.
	Stati []*Status `json:"Stati,omitempty"`
	// Failures holds the value of the Failures edge.
	Failures []*Failure `json:"Failures,omitempty"`
	// Files holds the value of the Files edge.
	Files []*File `json:"Files,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int

	namedCounters map[string][]*Counter
	namedStati    map[string][]*Status
	namedFailures map[string][]*Failure
	namedFiles    map[string][]*File
}

// CountersOrErr returns the Counters value or an error if the edge
// was not loaded in eager-loading.
func (e AlertEdges) CountersOrErr() ([]*Counter, error) {
	if e.loadedTypes[0] {
		return e.Counters, nil
	}
	return nil, &NotLoadedError{edge: "Counters"}
}

// StatiOrErr returns the Stati value or an error if the edge
// was not loaded in eager-loading.
func (e AlertEdges) StatiOrErr() ([]*Status, error) {
	if e.loadedTypes[1] {
		return e.Stati, nil
	}
	return nil, &NotLoadedError{edge: "Stati"}
}

// FailuresOrErr returns the Failures value or an error if the edge
// was not loaded in eager-loading.
func (e AlertEdges) FailuresOrErr() ([]*Failure, error) {
	if e.loadedTypes[2] {
		return e.Failures, nil
	}
	return nil, &NotLoadedError{edge: "Failures"}
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e AlertEdges) FilesOrErr() ([]*File, error) {
	if e.loadedTypes[3] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "Files"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Alert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alert.FieldID, alert.FieldIntLevel:
			values[i] = new(sql.NullInt64)
		case alert.FieldName, alert.FieldUsername, alert.FieldRegion, alert.FieldProbeOS, alert.FieldProbeHost, alert.FieldError:
			values[i] = new(sql.NullString)
		case alert.FieldTime:
			values[i] = new(sql.NullTime)
		case alert.FieldUUID, alert.FieldIncidentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Alert fields.
func (_m *Alert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alert.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case alert.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field UUID", values[i])
			} else if value != nil {
				_m.UUID = *value
			}
		case alert.FieldIncidentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field IncidentID", values[i])
			} else if value != nil {
				_m.IncidentID = *value
			}
		case alert.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case alert.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Time", values[i])
			} else if value.Valid {
				_m.Time = value.Time
			}
		case alert.FieldIntLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field IntLevel", values[i])
			} else if value.Valid {
				_m.IntLevel = int(value.Int64)
			}
		case alert.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case alert.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case alert.FieldProbeOS:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProbeOS", values[i])
			} else if value.Valid {
				_m.ProbeOS = value.String
			}
		case alert.FieldProbeHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProbeHost", values[i])
			} else if value.Valid {
				_m.ProbeHost = value.String
			}
		case alert.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Alert.
// This includes values selected through modifiers, order, etc.
func (_m *Alert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCounters queries the "Counters" edge of the Alert entity.
func (_m *Alert) QueryCounters() *CounterQuery {
	return NewAlertClient(_m.config).QueryCounters(_m)
}

// QueryStati queries the "Stati" edge of the Alert entity.
func (_m *Alert) QueryStati() *StatusQuery {
	return NewAlertClient(_m.config).QueryStati(_m)
}

// QueryFailures queries the "Failures" edge of the Alert entity.
func (_m *Alert) QueryFailures() *FailureQuery {
	return NewAlertClient(_m.config).QueryFailures(_m)
}

// QueryFiles queries the "Files" edge of the Alert entity.
func (_m *Alert) QueryFiles() *FileQuery {
	return NewAlertClient(_m.config).QueryFiles(_m)
}

// Update returns a builder for updating this Alert.
// Note that you need to call Alert.Unwrap() before calling this method if this Alert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Alert) Update() *AlertUpdateOne {
	return NewAlertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Alert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Alert) Unwrap() *Alert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Alert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Alert) String() string {
	var builder strings.Builder
	builder.WriteString("Alert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("UUID=")
	builder.WriteString(fmt.Sprintf("%v", _m.UUID))
	builder.WriteString(", ")
	builder.WriteString("IncidentID=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncidentID))
	builder.WriteString(", ")
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("Time=")
	builder.WriteString(_m.Time.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("IntLevel=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntLevel))
	builder.WriteString(", ")
	builder.WriteString("Username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("Region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("ProbeOS=")
	builder.WriteString(_m.ProbeOS)
	builder.WriteString(", ")
	builder.WriteString("ProbeHost=")
	builder.WriteString(_m.ProbeHost)
	builder.WriteString(", ")
	builder.WriteString("Error=")
	builder.WriteString(_m.Error)
	builder.WriteByte(')')
	return builder.String()
}

// NamedCounters returns the Counters named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Alert) NamedCounters(name string) ([]*Counter, error) {
	if _m.Edges.namedCounters == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedCounters[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Alert) appendNamedCounters(name string, edges ...*Counter) {
	if _m.Edges.namedCounters == nil {
		_m.Edges.namedCounters = make(map[string][]*Counter)
	}
	if len(edges) == 0 {
		_m.Edges.namedCounters[name] = []*Counter{}
	} else {
		_m.Edges.namedCounters[name] = append(_m.Edges.namedCounters[name], edges...)
	}
}

// NamedStati returns the Stati named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Alert) NamedStati(name string) ([]*Status, error) {
	if _m.Edges.namedStati == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedStati[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Alert) appendNamedStati(name string, edges ...*Status) {
	if _m.Edges.namedStati == nil {
		_m.Edges.namedStati = make(map[string][]*Status)
	}
	if len(edges) == 0 {
		_m.Edges.namedStati[name] = []*Status{}
	} else {
		_m.Edges.namedStati[name] = append(_m.Edges.namedStati[name], edges...)
	}
}

// NamedFailures returns the Failures named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Alert) NamedFailures(name string) ([]*Failure, error) {
	if _m.Edges.namedFailures == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedFailures[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Alert) appendNamedFailures(name string, edges ...*Failure) {
	if _m.Edges.namedFailures == nil {
		_m.Edges.namedFailures = make(map[string][]*Failure)
	}
	if len(edges) == 0 {
		_m.Edges.namedFailures[name] = []*Failure{}
	} else {
		_m.Edges.namedFailures[name] = append(_m.Edges.namedFailures[name], edges...)
	}
}

// NamedFiles returns the Files named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Alert) NamedFiles(name string) ([]*File, error) {
	if _m.Edges.namedFiles == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedFiles[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Alert) appendNamedFiles(name string, edges ...*File) {
	if _m.Edges.namedFiles == nil {
		_m.Edges.namedFiles = make(map[string][]*File)
	}
	if len(edges) == 0 {
		_m.Edges.namedFiles[name] = []*File{}
	} else {
		_m.Edges.namedFiles[name] = append(_m.Edges.namedFiles[name], edges...)
	}
}

// Alerts is a parsable slice of Alert.
type Alerts []*Alert
