// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/counter"
)

// CounterCreate is the builder for creating a Counter entity.
type CounterCreate struct {
	config
	mutation *CounterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "Name" field.
func (_c *CounterCreate) SetName(v string) *CounterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetValue sets the "Value" field.
func (_c *CounterCreate) SetValue(v float64) *CounterCreate {
	_c.mutation.SetValue(v)
	return _c
}

// Mutation returns the CounterMutation object of the builder.
func (_c *CounterCreate) Mutation() *CounterMutation {
	return _c.mutation
}

// Save creates the Counter in the database.
func (_c *CounterCreate) Save(ctx context.Context) (*Counter, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CounterCreate) SaveX(ctx context.Context) *Counter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CounterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CounterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CounterCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "Counter.Name"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "Value", err: errors.New(`ent: missing required field "Counter.Value"`)}
	}
	return nil
}

func (_c *CounterCreate) sqlSave(ctx context.Context) (*Counter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CounterCreate) createSpec() (*Counter, *sqlgraph.CreateSpec) {
	var (
		_node = &Counter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(counter.Table, sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(counter.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(counter.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Counter.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CounterUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CounterCreate) OnConflict(opts ...sql.ConflictOption) *CounterUpsertOne {
	_c.conflict = opts
	return &CounterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CounterCreate) OnConflictColumns(columns ...string) *CounterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CounterUpsertOne{
		create: _c,
	}
}

type (
	// CounterUpsertOne is the builder for "upsert"-ing
	//  one Counter node.
	CounterUpsertOne struct {
		create *CounterCreate
	}

	// CounterUpsert is the "OnConflict" setter.
	CounterUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "Name" field.
func (u *CounterUpsert) SetName(v string) *CounterUpsert {
	u.Set(counter.FieldName, v)
	return u
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *CounterUpsert) UpdateName() *CounterUpsert {
	u.SetExcluded(counter.FieldName)
	return u
}

// SetValue sets the "Value" field.
func (u *CounterUpsert) SetValue(v float64) *CounterUpsert {
	u.Set(counter.FieldValue, v)
	return u
}

// UpdateValue sets the "Value" field to the value that was provided on create.
func (u *CounterUpsert) UpdateValue() *CounterUpsert {
	u.SetExcluded(counter.FieldValue)
	return u
}

// AddValue adds v to the "Value" field.
func (u *CounterUpsert) AddValue(v float64) *CounterUpsert {
	u.Add(counter.FieldValue, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CounterUpsertOne) UpdateNewValues() *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Counter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CounterUpsertOne) Ignore() *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CounterUpsertOne) DoNothing() *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CounterCreate.OnConflict
// documentation for more info.
func (u *CounterUpsertOne) Update(set func(*CounterUpsert)) *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CounterUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "Name" field.
func (u *CounterUpsertOne) SetName(v string) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateName() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateName()
	})
}

// SetValue sets the "Value" field.
func (u *CounterUpsertOne) SetValue(v float64) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "Value" field.
func (u *CounterUpsertOne) AddValue(v float64) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "Value" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateValue() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *CounterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CounterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CounterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CounterUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CounterUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CounterCreateBulk is the builder for creating many Counter entities in bulk.
type CounterCreateBulk struct {
	config
	err      error
	builders []*CounterCreate
	conflict []sql.ConflictOption
}

// Save creates the Counter entities in the database.
func (_c *CounterCreateBulk) Save(ctx context.Context) ([]*Counter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Counter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CounterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CounterCreateBulk) SaveX(ctx context.Context) []*Counter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CounterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CounterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Counter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CounterUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CounterCreateBulk) OnConflict(opts ...sql.ConflictOption) *CounterUpsertBulk {
	_c.conflict = opts
	return &CounterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CounterCreateBulk) OnConflictColumns(columns ...string) *CounterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CounterUpsertBulk{
		create: _c,
	}
}

// CounterUpsertBulk is the builder for "upsert"-ing
// a bulk of Counter nodes.
type CounterUpsertBulk struct {
	create *CounterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CounterUpsertBulk) UpdateNewValues() *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CounterUpsertBulk) Ignore() *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CounterUpsertBulk) DoNothing() *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CounterCreateBulk.OnConflict
// documentation for more info.
func (u *CounterUpsertBulk) Update(set func(*CounterUpsert)) *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CounterUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "Name" field.
func (u *CounterUpsertBulk) SetName(v string) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateName() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateName()
	})
}

// SetValue sets the "Value" field.
func (u *CounterUpsertBulk) SetValue(v float64) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "Value" field.
func (u *CounterUpsertBulk) AddValue(v float64) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "Value" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateValue() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *CounterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CounterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CounterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CounterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
