// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/failure"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/predicate"
)

// FailureUpdate is the builder for updating Failure entities.
type FailureUpdate struct {
	config
	hooks    []Hook
	mutation *FailureMutation
}

// Where appends a list predicates to the FailureUpdate builder.
func (_u *FailureUpdate) Where(ps ...predicate.Failure) *FailureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetError sets the "Error" field.
func (_u *FailureUpdate) SetError(v string) *FailureUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "Error" field if the given value is not nil.
func (_u *FailureUpdate) SetNillableError(v *string) *FailureUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdx sets the "Idx" field.
func (_u *FailureUpdate) SetIdx(v int) *FailureUpdate {
	_u.mutation.ResetIdx()
	_u.mutation.SetIdx(v)
	return _u
}

// SetNillableIdx sets the "Idx" field if the given value is not nil.
func (_u *FailureUpdate) SetNillableIdx(v *int) *FailureUpdate {
	if v != nil {
		_u.SetIdx(*v)
	}
	return _u
}

// AddIdx adds value to the "Idx" field.
func (_u *FailureUpdate) AddIdx(v int) *FailureUpdate {
	_u.mutation.AddIdx(v)
	return _u
}

// Mutation returns the FailureMutation object of the builder.
func (_u *FailureUpdate) Mutation() *FailureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FailureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FailureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FailureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FailureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FailureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(failure.Table, failure.Columns, sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(failure.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Idx(); ok {
		_spec.SetField(failure.FieldIdx, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIdx(); ok {
		_spec.AddField(failure.FieldIdx, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{failure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FailureUpdateOne is the builder for updating a single Failure entity.
type FailureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FailureMutation
}

// SetError sets the "Error" field.
func (_u *FailureUpdateOne) SetError(v string) *FailureUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "Error" field if the given value is not nil.
func (_u *FailureUpdateOne) SetNillableError(v *string) *FailureUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdx sets the "Idx" field.
func (_u *FailureUpdateOne) SetIdx(v int) *FailureUpdateOne {
	_u.mutation.ResetIdx()
	_u.mutation.SetIdx(v)
	return _u
}

// SetNillableIdx sets the "Idx" field if the given value is not nil.
func (_u *FailureUpdateOne) SetNillableIdx(v *int) *FailureUpdateOne {
	if v != nil {
		_u.SetIdx(*v)
	}
	return _u
}

// AddIdx adds value to the "Idx" field.
func (_u *FailureUpdateOne) AddIdx(v int) *FailureUpdateOne {
	_u.mutation.AddIdx(v)
	return _u
}

// Mutation returns the FailureMutation object of the builder.
func (_u *FailureUpdateOne) Mutation() *FailureMutation {
	return _u.mutation
}

// Where appends a list predicates to the FailureUpdate builder.
func (_u *FailureUpdateOne) Where(ps ...predicate.Failure) *FailureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FailureUpdateOne) Select(field string, fields ...string) *FailureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Failure entity.
func (_u *FailureUpdateOne) Save(ctx context.Context) (*Failure, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FailureUpdateOne) SaveX(ctx context.Context) *Failure {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FailureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FailureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FailureUpdateOne) sqlSave(ctx context.Context) (_node *Failure, err error) {
	_spec := sqlgraph.NewUpdateSpec(failure.Table, failure.Columns, sqlgraph.NewFieldSpec(failure.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Failure.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, failure.FieldID)
		for _, f := range fields {
			if !failure.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != failure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(failure.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Idx(); ok {
		_spec.SetField(failure.FieldIdx, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIdx(); ok {
		_spec.AddField(failure.FieldIdx, field.TypeInt, value)
	}
	_node = &Failure{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{failure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
