// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/file"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/predicate"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUUID sets the "UUID" field.
func (_u *FileUpdate) SetUUID(v uuid.UUID) *FileUpdate {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "UUID" field if the given value is not nil.
func (_u *FileUpdate) SetNillableUUID(v *uuid.UUID) *FileUpdate {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetName sets the "Name" field.
func (_u *FileUpdate) SetName(v string) *FileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *FileUpdate) SetNillableName(v *string) *FileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "Type" field.
func (_u *FileUpdate) SetType(v string) *FileUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "Type" field if the given value is not nil.
func (_u *FileUpdate) SetNillableType(v *string) *FileUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetExt sets the "Ext" field.
func (_u *FileUpdate) SetExt(v string) *FileUpdate {
	_u.mutation.SetExt(v)
	return _u
}

// SetNillableExt sets the "Ext" field if the given value is not nil.
func (_u *FileUpdate) SetNillableExt(v *string) *FileUpdate {
	if v != nil {
		_u.SetExt(*v)
	}
	return _u
}

// SetSize sets the "Size" field.
func (_u *FileUpdate) SetSize(v int) *FileUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "Size" field if the given value is not nil.
func (_u *FileUpdate) SetNillableSize(v *int) *FileUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "Size" field.
func (_u *FileUpdate) AddSize(v int) *FileUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *FileUpdate) SetPayload(v []byte) *FileUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdate) Mutation() *FileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(file.FieldUUID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(file.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(file.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ext(); ok {
		_spec.SetField(file.FieldExt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(file.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(file.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(file.FieldPayload, field.TypeBytes, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileMutation
}

// SetUUID sets the "UUID" field.
func (_u *FileUpdateOne) SetUUID(v uuid.UUID) *FileUpdateOne {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "UUID" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableUUID(v *uuid.UUID) *FileUpdateOne {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetName sets the "Name" field.
func (_u *FileUpdateOne) SetName(v string) *FileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableName(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "Type" field.
func (_u *FileUpdateOne) SetType(v string) *FileUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "Type" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableType(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetExt sets the "Ext" field.
func (_u *FileUpdateOne) SetExt(v string) *FileUpdateOne {
	_u.mutation.SetExt(v)
	return _u
}

// SetNillableExt sets the "Ext" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableExt(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetExt(*v)
	}
	return _u
}

// SetSize sets the "Size" field.
func (_u *FileUpdateOne) SetSize(v int) *FileUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "Size" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableSize(v *int) *FileUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "Size" field.
func (_u *FileUpdateOne) AddSize(v int) *FileUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *FileUpdateOne) SetPayload(v []byte) *FileUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdateOne) Mutation() *FileMutation {
	return _u.mutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdateOne) Where(ps ...predicate.File) *FileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUpdateOne) Select(field string, fields ...string) *FileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated File entity.
func (_u *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "File.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, file.FieldID)
		for _, f := range fields {
			if !file.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != file.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(file.FieldUUID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(file.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(file.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ext(); ok {
		_spec.SetField(file.FieldExt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(file.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(file.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(file.FieldPayload, field.TypeBytes, value)
	}
	_node = &File{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
