// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/counter"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/failure"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/file"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/incident"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/predicate"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/status"
)

// IncidentQuery is the builder for querying Incident entities.
type IncidentQuery struct {
	config
	ctx               *QueryContext
	order             []incident.OrderOption
	inters            []Interceptor
	predicates        []predicate.Incident
	withCounters      *CounterQuery
	withStati         *StatusQuery
	withFailures      *FailureQuery
	withFiles         *FileQuery
	modifiers         []func(*sql.Selector)
	loadTotal         []func(context.Context, []*Incident) error
	withNamedCounters map[string]*CounterQuery
	withNamedStati    map[string]*StatusQuery
	withNamedFailures map[string]*FailureQuery
	withNamedFiles    map[string]*FileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IncidentQuery builder.
func (_q *IncidentQuery) Where(ps ...predicate.Incident) *IncidentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *IncidentQuery) Limit(limit int) *IncidentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *IncidentQuery) Offset(offset int) *IncidentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IncidentQuery) Unique(unique bool) *IncidentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *IncidentQuery) Order(o ...incident.OrderOption) *IncidentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCounters chains the current query on the "Counters" edge.
func (_q *IncidentQuery) QueryCounters() *CounterQuery {
	query := (&CounterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(incident.Table, incident.FieldID, selector),
			sqlgraph.To(counter.Table, counter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, incident.CountersTable, incident.CountersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStati chains the current query on the "Stati" edge.
func (_q *IncidentQuery) QueryStati() *StatusQuery {
	query := (&StatusClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(incident.Table, incident.FieldID, selector),
			sqlgraph.To(status.Table, status.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, incident.StatiTable, incident.StatiColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFailures chains the current query on the "Failures" edge.
func (_q *IncidentQuery) QueryFailures() *FailureQuery {
	query := (&FailureClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(incident.Table, incident.FieldID, selector),
			sqlgraph.To(failure.Table, failure.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, incident.FailuresTable, incident.FailuresColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFiles chains the current query on the "Files" edge.
func (_q *IncidentQuery) QueryFiles() *FileQuery {
	query := (&FileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(incident.Table, incident.FieldID, selector),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, incident.FilesTable, incident.FilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Incident entity from the query.
// Returns a *NotFoundError when no Incident was found.
func (_q *IncidentQuery) First(ctx context.Context) (*Incident, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{incident.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *IncidentQuery) FirstX(ctx context.Context) *Incident {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Incident ID from the query.
// Returns a *NotFoundError when no Incident ID was found.
func (_q *IncidentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{incident.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IncidentQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Incident entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Incident entity is found.
// Returns a *NotFoundError when no Incident entities are found.
func (_q *IncidentQuery) Only(ctx context.Context) (*Incident, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{incident.Label}
	default:
		return nil, &NotSingularError{incident.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *IncidentQuery) OnlyX(ctx context.Context) *Incident {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Incident ID in the query.
// Returns a *NotSingularError when more than one Incident ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IncidentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{incident.Label}
	default:
		err = &NotSingularError{incident.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IncidentQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Incidents.
func (_q *IncidentQuery) All(ctx context.Context) ([]*Incident, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Incident, *IncidentQuery]()
	return withInterceptors[[]*Incident](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *IncidentQuery) AllX(ctx context.Context) []*Incident {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Incident IDs.
func (_q *IncidentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(incident.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *IncidentQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *IncidentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*IncidentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *IncidentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *IncidentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *IncidentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IncidentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IncidentQuery) Clone() *IncidentQuery {
	if _q == nil {
		return nil
	}
	return &IncidentQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]incident.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Incident{}, _q.predicates...),
		withCounters: _q.withCounters.Clone(),
		withStati:    _q.withStati.Clone(),
		withFailures: _q.withFailures.Clone(),
		withFiles:    _q.withFiles.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCounters tells the query-builder to eager-load the nodes that are connected to
// the "Counters" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithCounters(opts ...func(*CounterQuery)) *IncidentQuery {
	query := (&CounterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCounters = query
	return _q
}

// WithStati tells the query-builder to eager-load the nodes that are connected to
// the "Stati" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithStati(opts ...func(*StatusQuery)) *IncidentQuery {
	query := (&StatusClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStati = query
	return _q
}

// WithFailures tells the query-builder to eager-load the nodes that are connected to
// the "Failures" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithFailures(opts ...func(*FailureQuery)) *IncidentQuery {
	query := (&FailureClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFailures = query
	return _q
}

// WithFiles tells the query-builder to eager-load the nodes that are connected to
// the "Files" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithFiles(opts ...func(*FileQuery)) *IncidentQuery {
	query := (&FileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFiles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"UUID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Incident.Query().
//		GroupBy(incident.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IncidentQuery) GroupBy(field string, fields ...string) *IncidentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IncidentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = incident.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"UUID,omitempty"`
//	}
//
//	client.Incident.Query().
//		Select(incident.FieldUUID).
//		Scan(ctx, &v)
func (_q *IncidentQuery) Select(fields ...string) *IncidentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IncidentSelect{IncidentQuery: _q}
	sbuild.label = incident.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IncidentSelect configured with the given aggregations.
func (_q *IncidentQuery) Aggregate(fns ...AggregateFunc) *IncidentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *IncidentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !incident.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *IncidentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Incident, error) {
	var (
		nodes       = []*Incident{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withCounters != nil,
			_q.withStati != nil,
			_q.withFailures != nil,
			_q.withFiles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Incident).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Incident{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCounters; query != nil {
		if err := _q.loadCounters(ctx, query, nodes,
			func(n *Incident) { n.Edges.Counters = []*Counter{} },
			func(n *Incident, e *Counter) { n.Edges.Counters = append(n.Edges.Counters, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStati; query != nil {
		if err := _q.loadStati(ctx, query, nodes,
			func(n *Incident) { n.Edges.Stati = []*Status{} },
			func(n *Incident, e *Status) { n.Edges.Stati = append(n.Edges.Stati, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFailures; query != nil {
		if err := _q.loadFailures(ctx, query, nodes,
			func(n *Incident) { n.Edges.Failures = []*Failure{} },
			func(n *Incident, e *Failure) { n.Edges.Failures = append(n.Edges.Failures, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFiles; query != nil {
		if err := _q.loadFiles(ctx, query, nodes,
			func(n *Incident) { n.Edges.Files = []*File{} },
			func(n *Incident, e *File) { n.Edges.Files = append(n.Edges.Files, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedCounters {
		if err := _q.loadCounters(ctx, query, nodes,
			func(n *Incident) { n.appendNamedCounters(name) },
			func(n *Incident, e *Counter) { n.appendNamedCounters(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedStati {
		if err := _q.loadStati(ctx, query, nodes,
			func(n *Incident) { n.appendNamedStati(name) },
			func(n *Incident, e *Status) { n.appendNamedStati(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedFailures {
		if err := _q.loadFailures(ctx, query, nodes,
			func(n *Incident) { n.appendNamedFailures(name) },
			func(n *Incident, e *Failure) { n.appendNamedFailures(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedFiles {
		if err := _q.loadFiles(ctx, query, nodes,
			func(n *Incident) { n.appendNamedFiles(name) },
			func(n *Incident, e *File) { n.appendNamedFiles(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *IncidentQuery) loadCounters(ctx context.Context, query *CounterQuery, nodes []*Incident, init func(*Incident), assign func(*Incident, *Counter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Incident)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Counter(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(incident.CountersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.incident_counters
		if fk == nil {
			return fmt.Errorf(`foreign-key "incident_counters" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "incident_counters" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *IncidentQuery) loadStati(ctx context.Context, query *StatusQuery, nodes []*Incident, init func(*Incident), assign func(*Incident, *Status)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Incident)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Status(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(incident.StatiColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.incident_stati
		if fk == nil {
			return fmt.Errorf(`foreign-key "incident_stati" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "incident_stati" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *IncidentQuery) loadFailures(ctx context.Context, query *FailureQuery, nodes []*Incident, init func(*Incident), assign func(*Incident, *Failure)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Incident)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Failure(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(incident.FailuresColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.incident_failures
		if fk == nil {
			return fmt.Errorf(`foreign-key "incident_failures" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "incident_failures" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *IncidentQuery) loadFiles(ctx context.Context, query *FileQuery, nodes []*Incident, init func(*Incident), assign func(*Incident, *File)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Incident)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.File(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(incident.FilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.incident_files
		if fk == nil {
			return fmt.Errorf(`foreign-key "incident_files" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "incident_files" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *IncidentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *IncidentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incident.FieldID)
		for i := range fields {
			if fields[i] != incident.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *IncidentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(incident.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = incident.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCounters tells the query-builder to eager-load the nodes that are connected to the "Counters"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithNamedCounters(name string, opts ...func(*CounterQuery)) *IncidentQuery {
	query := (&CounterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedCounters == nil {
		_q.withNamedCounters = make(map[string]*CounterQuery)
	}
	_q.withNamedCounters[name] = query
	return _q
}

// WithNamedStati tells the query-builder to eager-load the nodes that are connected to the "Stati"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithNamedStati(name string, opts ...func(*StatusQuery)) *IncidentQuery {
	query := (&StatusClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedStati == nil {
		_q.withNamedStati = make(map[string]*StatusQuery)
	}
	_q.withNamedStati[name] = query
	return _q
}

// WithNamedFailures tells the query-builder to eager-load the nodes that are connected to the "Failures"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithNamedFailures(name string, opts ...func(*FailureQuery)) *IncidentQuery {
	query := (&FailureClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedFailures == nil {
		_q.withNamedFailures = make(map[string]*FailureQuery)
	}
	_q.withNamedFailures[name] = query
	return _q
}

// WithNamedFiles tells the query-builder to eager-load the nodes that are connected to the "Files"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *IncidentQuery) WithNamedFiles(name string, opts ...func(*FileQuery)) *IncidentQuery {
	query := (&FileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedFiles == nil {
		_q.withNamedFiles = make(map[string]*FileQuery)
	}
	_q.withNamedFiles[name] = query
	return _q
}

// IncidentGroupBy is the group-by builder for Incident entities.
type IncidentGroupBy struct {
	selector
	build *IncidentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IncidentGroupBy) Aggregate(fns ...AggregateFunc) *IncidentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *IncidentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IncidentQuery, *IncidentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *IncidentGroupBy) sqlScan(ctx context.Context, root *IncidentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IncidentSelect is the builder for selecting fields of Incident entities.
type IncidentSelect struct {
	*IncidentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IncidentSelect) Aggregate(fns ...AggregateFunc) *IncidentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *IncidentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IncidentQuery, *IncidentSelect](ctx, _s.IncidentQuery, _s, _s.inters, v)
}

func (_s *IncidentSelect) sqlScan(ctx context.Context, root *IncidentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
