// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/predicate"
	"github.com/vogtp/som/pkg/visualiser/webstatus/db/ent/status"
)

// StatusUpdate is the builder for updating Status entities.
type StatusUpdate struct {
	config
	hooks    []Hook
	mutation *StatusMutation
}

// Where appends a list predicates to the StatusUpdate builder.
func (_u *StatusUpdate) Where(ps ...predicate.Status) *StatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "Name" field.
func (_u *StatusUpdate) SetName(v string) *StatusUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableName(v *string) *StatusUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetValue sets the "Value" field.
func (_u *StatusUpdate) SetValue(v string) *StatusUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "Value" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableValue(v *string) *StatusUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the StatusMutation object of the builder.
func (_u *StatusUpdate) Mutation() *StatusMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(status.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(status.FieldValue, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusUpdateOne is the builder for updating a single Status entity.
type StatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusMutation
}

// SetName sets the "Name" field.
func (_u *StatusUpdateOne) SetName(v string) *StatusUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableName(v *string) *StatusUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetValue sets the "Value" field.
func (_u *StatusUpdateOne) SetValue(v string) *StatusUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "Value" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableValue(v *string) *StatusUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the StatusMutation object of the builder.
func (_u *StatusUpdateOne) Mutation() *StatusMutation {
	return _u.mutation
}

// Where appends a list predicates to the StatusUpdate builder.
func (_u *StatusUpdateOne) Where(ps ...predicate.Status) *StatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusUpdateOne) Select(field string, fields ...string) *StatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Status entity.
func (_u *StatusUpdateOne) Save(ctx context.Context) (*Status, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusUpdateOne) SaveX(ctx context.Context) *Status {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StatusUpdateOne) sqlSave(ctx context.Context) (_node *Status, err error) {
	_spec := sqlgraph.NewUpdateSpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Status.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, status.FieldID)
		for _, f := range fields {
			if !status.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != status.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(status.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(status.FieldValue, field.TypeString, value)
	}
	_node = &Status{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
